# Numpy: Package for Multidimensional array
## Vector(1d)
### Matrix(2d or 1d)

In [1]:
import numpy as np # importing numpy, and giving it the alias np

##### Simple Tasks

In [2]:
# Transforming a list into a numpy array
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [ ]:
arr=np.array([1,2,3]) # creating a numpy array
arr

In [ ]:
# Transforming a list of lists(2d list) into a numpy array(2d array)
list_of_lists=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
np.array(list_of_lists)

In [4]:
# Its like range() function, but it returns a numpy array
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(5,30,5) # 5 is the start, 30 is the end, 5 is the step

In [ ]:
np.zeros(100) # creates a numpy array of 100 zeros

In [ ]:
np.zeros(10,dtype=int) # creates a numpy array of 10 zeros, but with int type

In [ ]:
np.ones((2,5)) # creates a 2x5 numpy array of ones

In [ ]:
# np.linspace(0,1,5) It returns 5 evenly spaced numbers between 0 and 1, which includes 0 and 1
np.linspace(0,1,5)

In [ ]:
np.linspace(0,1,5,endpoint=False), # endpoint=False means it will not include 1

In [ ]:
np.linspace(0,1,6)

In [ ]:
l1 = np.linspace(0,20,8) #step = (20-0)/7 = 2.857142857142857
l2 = np.linspace(0,20,9) #step = (20-0)/8 = 2.5
l1,l2

##### Matrix Formation

In [ ]:
np.eye(10,dtype=int)  # creates a 10x10 numpy array which is identity matrix

In [ ]:
np.random.rand(2,4) # It returns a 2x4 array of random numbers between 0 and 1

In [ ]:
np.random.randn(2,4) # It returns a 2x4 array of random numbers from standard normal distribution

In [ ]:
np.random.randint(2,10) # It returns a random integer between 2 and 10

In [ ]:
np.random.randint(20,56,100)

In [ ]:
sample_array=np.arange(30)
sample_array

In [ ]:
rand_array=np.random.randint(0,100,20)
rand_array

In [ ]:
sample_array.reshape(5,6)

In [ ]:
rand_array.min()

In [ ]:
rand_array.argmin()

In [ ]:
sample_array 

In [ ]:
sample_array.shape # It returns the shape of the array

In [ ]:
sample_array.reshape(5,6) # It returns a 5x6 array 

In [ ]:
sample_array.dtype # It returns the data type of the array

##### Some more matrix operations

In [ ]:
a=np.eye(5)
a

In [ ]:
a.T # It returns the transpose of the array

In [ ]:
a=np.random.rand(2,3) # It returns a 2x3 array of random numbers between 0 and 1
a

In [ ]:
a.T     # It returns the transpose of the array

In [36]:
import numpy as np

In [37]:
sample_array=np.arange(10,21) # It returns an array of numbers between 10 and 20
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [38]:
sample_array[8] # It returns the 8th element of the array

18

In [39]:
sample_array[2:5] # It returns the elements from 2nd to 4th index

array([12, 13, 14])

In [40]:
sample_array[1:4]=100 # It changes the elements from 1st to 3rd index to 100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [41]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
sample_array[0:7] # It returns the elements from 0th to 6th index

In [42]:
subset_sample_array=sample_array[0:7] # It returns the elements from 0th to 6th index
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [45]:
subset_sample_array[:]=1001 # It changes the elements from 0th to 6th index to 1001
# We can see that the changes are also reflected in the original array
subset_sample_array , sample_array

(array([1001, 1001, 1001, 1001, 1001, 1001, 1001]),
 array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20]))

### Two-Dimensional array

In [ ]:
import numpy as np

In [ ]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

In [ ]:
sample_matrix[0][2] # printing 1

In [ ]:
sample_matrix[2,:] # printing 3rd row

In [ ]:
sample_matrix[2] # printing 3rd row

In [ ]:
sample_matrix[:,2] # printing 3rd column

### Custom indexing

In [ ]:
sample_matrix=np.array(([30,10,1,23],[24,21,32,33],[6,76,24,7]))
sample_matrix

In [ ]:
sample_matrix[:,(3,2)]

###  Selection techniques

In [ ]:
sample_array=np.arange(1,31)
sample_array

In [ ]:
bool=sample_array<10
bool

In [ ]:
sample_array[bool]

In [ ]:
sample_array+sample_array

In [ ]:
np.exp(sample_array)

In [ ]:
np.sqrt(sample_array)

In [ ]:
np.log(sample_array)

In [ ]:
np.max(sample_array)

In [ ]:
np.min(sample_array)

In [ ]:
np.argmax(sample_array)

In [ ]:
np.argmin(sample_array)

In [ ]:
np.square(sample_array)

In [ ]:
np.std(sample_array)

In [ ]:
np.var(sample_array)


In [ ]:
np.mean(sample_array)

In [ ]:
array=np.random.randn(3,6)
array

In [ ]:
np.round(array,decimals=2)

In [51]:
sports=np.array(['golf','cricket','fball','cricket'])
sports_repeat= np.array(['golf','cricket','fball','cricket','cricket','cricket','cricket','cricket','cricket','cricket'])
np.unique(sports), np.unique(sports)

(array(['cricket', 'fball', 'golf'], dtype='<U7'),
 array(['cricket', 'fball', 'golf'], dtype='<U7'))

#### Pandas

In [ ]:
import pandas as pd # importing pandas, and renaming it as pd ( for convenience)
import numpy as np

In [52]:
labels=['w','x','y','z']
sample_list=[10,20,30,40]
array=np.array([1,2,3,4])
dict={'w':10,'x':20,'y':30,'z':40} # dictionary
# smarter way to create a dictionary
dict = {key:value for key,value in zip(labels,sample_list)}
dict


{'w': 10, 'x': 20, 'y': 30, 'z': 40}

In [ ]:
pd.Series(data=sample_list) # It will create a series with default index

In [ ]:
pd.Series(data=sample_list,index=labels) # It will create a series with custom index

In [ ]:
pd.Series(array,labels)

In [ ]:
pd.Series(dict)

##### Pandas dataframe and indexing

In [54]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [ ]:
sports1['football']

In [ ]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

In [ ]:
sports1+sports2

In [53]:
df1=pd.DataFrame(np.random.randn(8,5),index='A B C D E F G H '.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1 # It will create a dataframe with random numbers, and custom index and columns


Score1    Score2    Score3    Score4    Score5
A -0.782019  0.402101  1.160753  0.530398 -1.302952
B  0.067790  0.612669  0.797581  0.007537 -1.656454
C -1.020976 -0.272863 -0.171317  1.138011  1.823249
D  0.290892 -2.090637 -0.430508 -0.807548 -0.750806
E  0.442173 -0.135445  0.027866  0.579949 -0.836387
F  1.000894 -1.221133 -1.231291  0.497514 -0.483292
G  0.546768 -1.676016 -0.378616  0.399888 -0.140247
H  0.327284  0.721633  0.796827 -1.674179  0.822630

In [ ]:
#  Creating a dataframe from a dictionary of lists
df2={'ID':['101','102','103','107','176'],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

#### File Input

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
import pandas as pd

In [ ]:
'''
df=pd.read_excel("Club Schedule.xlsx")
df.head()
df.info()
df.describe()
'''

#### Pandas

In [4]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Premalatha-success/Yhills_June_2/main/auto-mpg.csv')
df.head(11)

mpg  cyl   disp   hp    wt   acc  yr  origin                   car name
0   18.0    8  307.0  130  3504  12.0  70       1  chevrolet chevelle malibu
1   15.0    8  350.0  165  3693  11.5  70       1          buick skylark 320
2   18.0    8  318.0  150  3436  11.0  70       1         plymouth satellite
3   16.0    8  304.0  150  3433  12.0  70       1              amc rebel sst
4   17.0    8  302.0  140  3449  10.5  70       1                ford torino
5   15.0    8  429.0  198  4341  10.0  70       1           ford galaxie 500
6   14.0    8  454.0  220  4354   9.0  70       1           chevrolet impala
7   14.0    8  440.0  215  4312   8.5  70       1          plymouth fury iii
8   14.0    8  455.0  225  4425  10.0  70       1           pontiac catalina
9   15.0    8  390.0  190  3850   8.5  70       1         amc ambassador dpl
10  15.0    8  383.0  170  3563  10.0  70       1        dodge challenger se

In [5]:
df.sample(5)

mpg  cyl   disp   hp    wt   acc  yr  origin              car name
251  20.2    8  302.0  139  3570  12.8  78       1  mercury monarch ghia
219  25.5    4  122.0   96  2300  15.5  77       1     plymouth arrow gs
250  19.4    8  318.0  140  3735  13.2  78       1        dodge diplomat
47   19.0    6  250.0  100  3282  15.0  71       1      pontiac firebird
76   18.0    4  121.0  112  2933  14.5  72       2       volvo 145e (sw)

In [11]:
print(f'''
1) df.columns: It returns the column names of the dataset
Columns in the dataset are: {df.columns}

2) df.shape : It returns the number of rows and columns in the dataset
Number of rows in the dataset are: {df.shape[0]}
Number of columns in the dataset are: {df.shape[1]}
df.shape returns a tuple of number of rows and columns in the dataset, which is {df.shape}

3) df.info(): It returns the following information about the dataset:
''')
df.info()


1) df.columns: It returns the column names of the dataset
Columns in the dataset are: Index(['mpg', 'cyl', 'disp', 'hp', 'wt', 'acc', 'yr', 'origin', 'car name'], dtype='object')

2) df.shape : It returns the number of rows and columns in the dataset
Number of rows in the dataset are: 398
Number of columns in the dataset are: 9
df.shape returns a tuple of number of rows and columns in the dataset, which is (398, 9)

3) df.info(): It returns the following information about the dataset:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   mpg       398 non-null    float64
 1   cyl       398 non-null    int64  
 2   disp      398 non-null    float64
 3   hp        398 non-null    object 
 4   wt        398 non-null    int64  
 5   acc       398 non-null    float64
 6   yr        398 non-null    int64  
 7   origin    398 non-null    int64  
 8   car name 

In [12]:
print(f'''
4) df.describe(): It returns the statistical information about the dataset
''')
df.describe()


4) df.describe(): It returns the statistical information about the dataset



mpg         cyl        disp           wt         acc  \
count  398.000000  398.000000  398.000000   398.000000  398.000000   
mean    23.514573    5.454774  193.425879  2970.424623   15.568090   
std      7.815984    1.701004  104.269838   846.841774    2.757689   
min      9.000000    3.000000   68.000000  1613.000000    8.000000   
25%     17.500000    4.000000  104.250000  2223.750000   13.825000   
50%     23.000000    4.000000  148.500000  2803.500000   15.500000   
75%     29.000000    8.000000  262.000000  3608.000000   17.175000   
max     46.600000    8.000000  455.000000  5140.000000   24.800000   

               yr      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

In [17]:
print(f'''
5) df.dtypes: It returns the data type of each column in the dataset
{df.dtypes}

6) df.nunique(): It returns the number of unique values in each column of the dataset
{df.nunique()}''')



5) df.dtypes: It returns the data type of each column in the dataset
mpg         float64
cyl           int64
disp        float64
hp           object
wt            int64
acc         float64
yr            int64
origin        int64
car name     object
dtype: object

6) df.nunique(): It returns the number of unique values in each column of the dataset
mpg         129
cyl           5
disp         82
hp           94
wt          351
acc          95
yr           13
origin        3
car name    305
dtype: int64


In [18]:

print(f'''
7) df.isnull().sum(): It returns the number of missing values in each column of the dataset
{df.isnull().sum()}

df.isnull().sum().sum(): It returns the total number of missing values in the dataset
Missing values in the dataset are: {df.isnull().sum().sum()}

Missing Values means empty cells in the dataset''')



7) df.isnull().sum(): It returns the number of missing values in each column of the dataset
mpg         0
cyl         0
disp        0
hp          0
wt          0
acc         0
yr          0
origin      0
car name    0
dtype: int64

df.isnull().sum().sum(): It returns the total number of missing values in the dataset
Missing values in the dataset are: 0

Missing Values means empty cells in the dataset


In [21]:
print(f'''
# Ways to select a column in a dataframe
1) df['column_name']: It returns the column as a series
2) df.column_name: It returns the column as a series
3) df[['column_name']]: It returns the column as a dataframe
4) df[['column_name1','column_name2']]: It returns the columns as a dataframe
''')
print(f'''
Dataframe vs Series:
1) Dataframe is a 2D data structure - It has rows and columns and headings. Its a tabular data structure
2) Series is a 1D data structure - It has only rows and no columns and no headings. Its a list of values
''')


# Ways to select a column in a dataframe
1) df['column_name']: It returns the column as a series
2) df.column_name: It returns the column as a series
3) df[['column_name']]: It returns the column as a dataframe
4) df[['column_name1','column_name2']]: It returns the columns as a dataframe


Dataframe vs Series:
1) Dataframe is a 2D data structure - It has rows and columns and headings. Its a tabular data structure
2) Series is a 1D data structure - It has only rows and no columns and no headings. Its a list of values



In [28]:
# example of selecting a column in a dataframe
print(f'''
1) df['column_name']: It returns the column as a series
{df['mpg'][:9]}
''')
print(f'''
2) df.column_name: It returns the column as a series as well
{df.mpg[:9]}
''')


1) df['column_name']: It returns the column as a series
0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
5    15.0
6    14.0
7    14.0
8    14.0
Name: mpg, dtype: float64


2) df.column_name: It returns the column as a series as well
0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
5    15.0
6    14.0
7    14.0
8    14.0
Name: mpg, dtype: float64



In [35]:
print(f'''
3) df[['column_name']]: It returns the column as a dataframe
{df[['mpg']].head(5)}
''')
# Utility is that we can use Dataframe methods with [[]], but not with [] or . :(
print(f'''
4) df[['column_name1','column_name2']]: It returns the columns as a dataframe
{df[['mpg','hp']].head(5)}
''')


3) df[['column_name']]: It returns the column as a dataframe
    mpg
0  18.0
1  15.0
2  18.0
3  16.0
4  17.0


4) df[['column_name1','column_name2']]: It returns the columns as a dataframe
    mpg   hp
0  18.0  130
1  15.0  165
2  18.0  150
3  16.0  150
4  17.0  140

